name: clean_architecture_posts_app
description: Posts App With Clean Architecture.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service locator
  get_it: ^7.6.0
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6
  # Local cache
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

